/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Pia Vargas, Amanda Demir
 * 
 * 
 * Klassen innehåller knappar som leder dig till nya fönster med olika funktioner
 * som du har som administratör.
 */
public class AdminSida extends javax.swing.JFrame {

    private static InfDB idb;
    
    public AdminSida(InfDB idb) {
        initComponents();
        this.idb = idb;
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        BTNnyregAgent = new java.awt.Button();
        BTNgeAdminstatus = new java.awt.Button();
        BTNsökAgentInfo = new java.awt.Button();
        BTNandraAgentinfo = new java.awt.Button();
        BTNandraKontorschef = new java.awt.Button();
        BTNandraOmradeschef = new java.awt.Button();
        BTNtabortUtrustning = new java.awt.Button();
        BTNtabortAgent = new java.awt.Button();
        BTNlosen = new java.awt.Button();
        BTNregutrust = new java.awt.Button();
        BTNsok = new java.awt.Button();
        BTNredALien = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        label1.setText("Meny för admin");

        BTNnyregAgent.setBackground(new java.awt.Color(255, 255, 255));
        BTNnyregAgent.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNnyregAgent.setLabel("Nyregistrera agent");
        BTNnyregAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNnyregAgentActionPerformed(evt);
            }
        });

        BTNgeAdminstatus.setBackground(new java.awt.Color(255, 255, 255));
        BTNgeAdminstatus.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNgeAdminstatus.setLabel("Ge administratörsstatus");
        BTNgeAdminstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNgeAdminstatusActionPerformed(evt);
            }
        });

        BTNsökAgentInfo.setBackground(new java.awt.Color(255, 255, 255));
        BTNsökAgentInfo.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNsökAgentInfo.setLabel("Sök agentinfo");
        BTNsökAgentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsökAgentInfoActionPerformed(evt);
            }
        });

        BTNandraAgentinfo.setBackground(new java.awt.Color(255, 255, 255));
        BTNandraAgentinfo.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNandraAgentinfo.setLabel("Ändra agentinfo");
        BTNandraAgentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNandraAgentinfoActionPerformed(evt);
            }
        });

        BTNandraKontorschef.setBackground(new java.awt.Color(255, 255, 255));
        BTNandraKontorschef.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNandraKontorschef.setLabel("Ändra kontorschef");
        BTNandraKontorschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNandraKontorschefActionPerformed(evt);
            }
        });

        BTNandraOmradeschef.setBackground(new java.awt.Color(255, 255, 255));
        BTNandraOmradeschef.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNandraOmradeschef.setLabel("Ändra omradeschef");
        BTNandraOmradeschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNandraOmradeschefActionPerformed(evt);
            }
        });

        BTNtabortUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        BTNtabortUtrustning.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNtabortUtrustning.setLabel("Ta bort utrustning");
        BTNtabortUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtabortUtrustningActionPerformed(evt);
            }
        });

        BTNtabortAgent.setBackground(new java.awt.Color(255, 255, 255));
        BTNtabortAgent.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNtabortAgent.setLabel("Ta bort agent");
        BTNtabortAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtabortAgentActionPerformed(evt);
            }
        });

        BTNlosen.setBackground(new java.awt.Color(255, 255, 255));
        BTNlosen.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNlosen.setLabel("Ändra lösenord");
        BTNlosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlosenActionPerformed(evt);
            }
        });

        BTNregutrust.setBackground(new java.awt.Color(255, 255, 255));
        BTNregutrust.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNregutrust.setLabel("Registrera utrustning");
        BTNregutrust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNregutrustActionPerformed(evt);
            }
        });

        BTNsok.setBackground(new java.awt.Color(255, 255, 255));
        BTNsok.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNsok.setLabel("Sök områdeschef");
        BTNsok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsokActionPerformed(evt);
            }
        });

        BTNredALien.setBackground(new java.awt.Color(255, 255, 255));
        BTNredALien.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNredALien.setLabel("Redigera alien");
        BTNredALien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNredALienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNnyregAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNgeAdminstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNsökAgentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNandraAgentinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNandraKontorschef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNandraOmradeschef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNtabortUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNtabortAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNsok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNregutrust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNlosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNredALien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNlosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNandraKontorschef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNnyregAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNregutrust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNandraOmradeschef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNgeAdminstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNsok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNtabortUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNsökAgentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNredALien, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTNtabortAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNandraAgentinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNnyregAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNnyregAgentActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan nyregistrera agenter.
        new NyregistreraAgent(idb).setVisible(true);
    }//GEN-LAST:event_BTNnyregAgentActionPerformed

    private void BTNandraKontorschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNandraKontorschefActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan ändra kontorschef.
        new AndraKontorschef(idb).setVisible(true);
    }//GEN-LAST:event_BTNandraKontorschefActionPerformed

    private void BTNgeAdminstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNgeAdminstatusActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan göra en eller flera agenter till administratörer.
        new GorAdministrator(idb).setVisible(true);
    }//GEN-LAST:event_BTNgeAdminstatusActionPerformed

    private void BTNandraOmradeschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNandraOmradeschefActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan uppdatera befintlig områdeschef.
        new AndraOmrodeschef(idb).setVisible(true);
    }//GEN-LAST:event_BTNandraOmradeschefActionPerformed

    private void BTNsökAgentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsökAgentInfoActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan visa information om vald agent.
        new VisaAgentInformation(idb).setVisible(true);
    }//GEN-LAST:event_BTNsökAgentInfoActionPerformed

    private void BTNtabortUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtabortUtrustningActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan radera utrustning från systemet.
        new RaderaUtrustning(idb).setVisible(true);
    }//GEN-LAST:event_BTNtabortUtrustningActionPerformed

    private void BTNandraAgentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNandraAgentinfoActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan ändra information på vald agent.
        new AndraAgentInformation(idb).setVisible(true);
    }//GEN-LAST:event_BTNandraAgentinfoActionPerformed

    private void BTNtabortAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtabortAgentActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan radera agent/er ur systemet.
        new RaderaAgent(idb).setVisible(true);
    }//GEN-LAST:event_BTNtabortAgentActionPerformed

    private void BTNlosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlosenActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan ändra lösenord.
        new AndraLosenAgent(idb).setVisible(true);
    }//GEN-LAST:event_BTNlosenActionPerformed

    private void BTNregutrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNregutrustActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan registrera ny utrustning.
        new NyregistreraUtrustning(idb).setVisible(true);
    }//GEN-LAST:event_BTNregutrustActionPerformed

    private void BTNsokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsokActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan hitta områdeschefer.
        new HittaOmradeschef(idb).setVisible(true);
    }//GEN-LAST:event_BTNsokActionPerformed

    private void BTNredALienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNredALienActionPerformed
        //Denna knapp leder dig till ett nytt fönster där du kan redigera Alien.
        new RedigeraAlien(idb).setVisible(true);
    }//GEN-LAST:event_BTNredALienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BTNandraAgentinfo;
    private java.awt.Button BTNandraKontorschef;
    private java.awt.Button BTNandraOmradeschef;
    private java.awt.Button BTNgeAdminstatus;
    private java.awt.Button BTNlosen;
    private java.awt.Button BTNnyregAgent;
    private java.awt.Button BTNredALien;
    private java.awt.Button BTNregutrust;
    private java.awt.Button BTNsok;
    private java.awt.Button BTNsökAgentInfo;
    private java.awt.Button BTNtabortAgent;
    private java.awt.Button BTNtabortUtrustning;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
