/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author piava, AmandaDemir
 */
public class AndraOmrodeschef extends javax.swing.JFrame {

     private InfDB idb;
    /**
     * Creates new form AndraOmrodeschef
     */
    public AndraOmrodeschef(InfDB idb) {
        initComponents();
        this.idb = idb;
        FyllCBOmrade();
        FyllCBAgent();
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JLOmradeschef = new javax.swing.JLabel();
        JLOmråde = new javax.swing.JLabel();
        CBvaljAgent = new javax.swing.JComboBox<>();
        CBomrade = new javax.swing.JComboBox<>();
        BtnAndra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel1.setText("Ändra information på områdeschef");

        JLOmradeschef.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLOmradeschef.setText("Välj områdeschef/agent:");

        JLOmråde.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLOmråde.setText("Välj område:");

        BtnAndra.setText("Ändra");
        BtnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAndraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        jLabel2.setText("Här kan du ändra information på områdeschef.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAndra)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JLOmradeschef)
                                    .addComponent(JLOmråde))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CBvaljAgent, 0, 112, Short.MAX_VALUE)
                                    .addComponent(CBomrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBvaljAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLOmradeschef))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBomrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLOmråde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(BtnAndra)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void FyllCBAgent() {
        String namnen = "SELECT namn from AGENT";
        ArrayList<String> agenter;

        try {
            agenter = idb.fetchColumn(namnen);
            for (String namn : agenter) {
                CBvaljAgent.addItem(namn);
            }
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }

    private void FyllCBOmrade() {
        String namnen = "Select Benamning from Omrade" ;
        ArrayList <String> Omraden;
        try {
             Omraden = idb.fetchColumn(namnen);
             
             for (String områden : Omraden) {
                 CBomrade.addItem(områden);
            }
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
   }
   
    private void BtnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAndraActionPerformed
        String omrade = CBomrade.getSelectedItem().toString();
        String agent = CBvaljAgent.getSelectedItem().toString();
        String ChefFraga = ("SELECT Namn FROM AGENT JOIN OMRADESCHEF ON AGENT.Agent_ID = OMRADESCHEF.Agent_ID JOIN OMRADE ON OMRADESCHEF.Omrade = OMRADE.Omrades_ID where benamning = '" + omrade + "'");
        String hamtaAgent = ("Select Agent_ID from agent where namn ='" + agent + "'");
        String hamtaOmraden = ("Select Omrades_ID from Omrade");
        String hamtaID = ("Select Omrades_ID from Omrade where Benamning ='" + omrade + "'");

        try {
            String chefForOmrode = idb.fetchSingle(ChefFraga);
            String hamtaOmradeID = idb.fetchSingle(hamtaID);
            String hamtaAgentID = idb.fetchSingle(hamtaAgent);
            int OmradesID = Integer.parseInt(hamtaOmradeID);
            int AgentID = Integer.parseInt(hamtaAgentID);
            String UppdateraChef = ("Update Omradeschef SET Agent_ID = " + AgentID + " where Omrade = " + OmradesID);
            idb.update(UppdateraChef);
             JOptionPane.showMessageDialog(null, "Chef uppdaterad");


            if (chefForOmrode.equals(agent)) {
                JOptionPane.showMessageDialog(null, "Agenten är redan chef för det området!");
            } 
            
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Agenten är redan chef för ett annat område.");
        }
    }//GEN-LAST:event_BtnAndraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraOmrodeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraOmrodeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraOmrodeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraOmrodeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AndraOmrodeschef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAndra;
    private javax.swing.JComboBox<String> CBomrade;
    private javax.swing.JComboBox<String> CBvaljAgent;
    private javax.swing.JLabel JLOmradeschef;
    private javax.swing.JLabel JLOmråde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
