/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException; 

/**
 *
 * @author piava
 */
public class LoggaIn extends javax.swing.JFrame {

    private static InfDB idb;
    private Validering validering;
    
    
    public LoggaIn(InfDB idb) {
        initComponents();
        this.idb = idb;
        validering = new Validering();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBrubrik = new javax.swing.JLabel();
        LBagentID = new javax.swing.JLabel();
        LBpassword = new javax.swing.JLabel();
        LoginUsername = new javax.swing.JTextField();
        LogInpassword = new javax.swing.JPasswordField();
        BTNlogin = new javax.swing.JButton();
        LBloginimage = new javax.swing.JLabel();
        LoginvaldAnvandare = new javax.swing.JComboBox<>();
        LBinloggningstyp = new javax.swing.JLabel();
        LBfelaktigt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        LBrubrik.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LBrubrik.setText("System login");
        LBrubrik.setToolTipText("");

        LBagentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBagentID.setText("Username:");

        LBpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBpassword.setText("Password:");

        LoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsernameActionPerformed(evt);
            }
        });

        LogInpassword.setText("jPasswordField1");
        LogInpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInpasswordActionPerformed(evt);
            }
        });

        BTNlogin.setText("Log in");
        BTNlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNloginActionPerformed(evt);
            }
        });

        LBloginimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MIBprojekt22/mibLogin.jpg"))); // NOI18N

        LoginvaldAnvandare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        LoginvaldAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginvaldAnvandareActionPerformed(evt);
            }
        });

        LBinloggningstyp.setText("Välj inloggningstyp:");

        LBfelaktigt.setText("Fel lösenord eller ID!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LogInpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(LBfelaktigt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNlogin)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBinloggningstyp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoginvaldAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBagentID)
                                .addGap(18, 18, 18)
                                .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LBrubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(98, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBloginimage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(LBloginimage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBrubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginvaldAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBinloggningstyp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBagentID)
                    .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBpassword)
                    .addComponent(LogInpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNlogin)
                    .addComponent(LBfelaktigt))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNloginActionPerformed
        LBfelaktigt.setText("");
        LoginUsername.requestFocus();
        String valdAnvandare = LoginvaldAnvandare.getSelectedItem().toString();
        String anvandare = LoginUsername.getText();
        String losenord = LogInpassword.getPassword();
      
    }//GEN-LAST:event_BTNloginActionPerformed

    private void LoginvaldAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginvaldAnvandareActionPerformed
    }//GEN-LAST:event_LoginvaldAnvandareActionPerformed

    private void LoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsernameActionPerformed

    private void LogInpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInpasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNlogin;
    private javax.swing.JLabel LBagentID;
    private javax.swing.JLabel LBfelaktigt;
    private javax.swing.JLabel LBinloggningstyp;
    private javax.swing.JLabel LBloginimage;
    private javax.swing.JLabel LBpassword;
    private javax.swing.JLabel LBrubrik;
    private javax.swing.JPasswordField LogInpassword;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JComboBox<String> LoginvaldAnvandare;
    // End of variables declaration//GEN-END:variables
}
