package MIBprojekt22;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException; 



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author piava
 */
public class LoggaIn extends javax.swing.JFrame {

    private InfDB idb;

    
    public LoggaIn(InfDB idb) {
        initComponents();
        this.idb = idb;
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }
   
     public void OppnaAgentSida() {
        AgentSida sidan = new AgentSida(idb);
        sidan.setVisible(true);
    }
     
     public void OppnaAdminSida(){
        AdminSida sidan = new AdminSida(idb);
        sidan.setVisible(true);
}
      public void OppnaAlienSida(){
        AlienSida sidan = new AlienSida(idb);
        sidan.setVisible(true);
}
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBfelaktigt = new javax.swing.JLabel();
        LBrubrik = new javax.swing.JLabel();
        LBagentID = new javax.swing.JLabel();
        LBpassword = new javax.swing.JLabel();
        LoginUsername = new javax.swing.JTextField();
        LogInpassword = new javax.swing.JPasswordField();
        LoginvaldAnvandare = new javax.swing.JComboBox<>();
        BTNloggain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBrubrik.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LBrubrik.setText("System login");
        LBrubrik.setToolTipText("");

        LBagentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBagentID.setText("Namn:");

        LBpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBpassword.setText("Lösenord:");

        LoginvaldAnvandare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alien", "Agent" }));

        BTNloggain.setText("Logga in");
        BTNloggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNloggainActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel1.setText("Välj inloggningstyp:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(LBfelaktigt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(LoginvaldAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBrubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LBagentID)
                                    .addComponent(LBpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LogInpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNloggain)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(LBrubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LoginvaldAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBagentID)
                    .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBpassword)
                    .addComponent(LogInpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(LBfelaktigt)
                .addGap(32, 32, 32)
                .addComponent(BTNloggain)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNloggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNloggainActionPerformed
        String valdAnvandare = LoginvaldAnvandare.getSelectedItem().toString();
        String inskrivetLosen = LogInpassword.getText();
        String inskrivetNamn = LoginUsername.getText();
        
        
        if (Validering.tomRuta(LoginUsername) && valdAnvandare.equals("Agent")) {
            try {
                String hamtaLosenord = ("SELECT Losenord from AGENT where namn = '" + inskrivetNamn + "'");
                String losenord = idb.fetchSingle(hamtaLosenord);

                String hamtaAdminstatus = ("Select Administrator from Agent where namn = '" + inskrivetNamn + "'");
                String status = idb.fetchSingle(hamtaAdminstatus);

                    if (losenord.equals(inskrivetLosen) && status.equals("N")) {
                    OppnaAgentSida();
                    this.dispose();
                }
                    if (losenord.equals(inskrivetLosen) && status.equals("J")) {
                    OppnaAdminSida();
                    this.dispose();
                }
                        } catch (InfException ettUndantag) {
                                JOptionPane.showMessageDialog(null, "Vänligen ange korrekta inloggsuppgifter!.");}
            }
        
        if (valdAnvandare.equals("Alien")){
            try {
                String inskrivetAlienLosen = LogInpassword.getText();
                String inskrivetAlienNamn = LoginUsername.getText();

            String hamtaLosenord = ("SELECT Losenord from ALIEN where namn = '"+ inskrivetAlienNamn +"'");
            String losenord = idb.fetchSingle(hamtaLosenord);

            if (losenord.equals(inskrivetAlienLosen)) {
                OppnaAlienSida();
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Inkorrekt lösenord");

            }
            } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något blev fel");
        }
        }
    }//GEN-LAST:event_BTNloggainActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNloggain;
    private javax.swing.JLabel LBagentID;
    private javax.swing.JLabel LBfelaktigt;
    private javax.swing.JLabel LBpassword;
    private javax.swing.JLabel LBrubrik;
    private javax.swing.JPasswordField LogInpassword;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JComboBox<String> LoginvaldAnvandare;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
