/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author piava, AmandaDemir
 */
public class NyregistreraAgent extends javax.swing.JFrame {
    
    private static InfDB idb;

    /**
     * Creates new form NyregistreraAgent1
     */
    public NyregistreraAgent(InfDB idb) {
        initComponents();
        this.idb = idb;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNamn = new javax.swing.JTextField();
        TxtTelnr = new javax.swing.JTextField();
        CBomrade = new javax.swing.JComboBox<>();
        JRubrik = new javax.swing.JLabel();
        TxtDatum = new javax.swing.JTextField();
        JLNamn = new javax.swing.JLabel();
        JLAdmin = new javax.swing.JLabel();
        JLLosen = new javax.swing.JLabel();
        JLTelnr = new javax.swing.JLabel();
        Txtlosen = new javax.swing.JTextField();
        JLOmråde = new javax.swing.JLabel();
        JLDatum = new javax.swing.JLabel();
        CBvaljAdmin = new javax.swing.JComboBox<>();
        BTNregistrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CBomrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Norrland", "Götaland", "Svealand" }));

        JRubrik.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        JRubrik.setText("Registrera Agent");

        JLNamn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLNamn.setText("Namn");

        JLAdmin.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLAdmin.setText("Admin");

        JLLosen.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLLosen.setText("Lösenord");

        JLTelnr.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLTelnr.setText("Tel.nr");

        JLOmråde.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLOmråde.setText("Område");

        JLDatum.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLDatum.setText("Anställningsdatum");

        CBvaljAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Ja", "Nej" }));

        BTNregistrera.setText("Registrera");
        BTNregistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNregistreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(JRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(TxtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JLTelnr, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLNamn)
                                        .addComponent(JLLosen))
                                    .addComponent(JLOmråde, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTelnr, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBomrade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtlosen, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JLDatum)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLAdmin)
                                        .addGap(86, 86, 86)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBvaljAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTNregistrera)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLNamn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLDatum)
                            .addComponent(TxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLAdmin)
                            .addComponent(CBvaljAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txtlosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLLosen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTelnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLTelnr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBomrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLOmråde))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(BTNregistrera)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNregistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNregistreraActionPerformed
        //Knappen registrerar en Agent om valideringen kontrolleras. 
        
        if (Validering.AgentNamn(TxtNamn) && (Validering.tomRuta(Txtlosen)) && (Validering.tomRuta(TxtDatum)) && (Validering.tomRuta(TxtTelnr))){
           
            String namn = TxtNamn.getText();
            String losen = Txtlosen.getText();
            String telnmr = TxtTelnr.getText();
            String admin = CBvaljAdmin.getSelectedItem().toString();
            String omrade = CBomrade.getSelectedItem().toString();
            String anstdatum = TxtDatum.getText();
            
                try {
                    String AID = idb.getAutoIncrement("Agent", "Agent_ID");
                    
                    int nyaID = Integer.parseInt(AID);
                    
                    String nuvarandeAdmin = "J";
                    String OmradesID = ("SELECT Omrades_ID FROM Omrade WHERE Benamning = '" + omrade + "'");
                    String hamtaOmradesID = idb.fetchSingle(OmradesID);
                    if (admin.equals("Ja")){
                        nuvarandeAdmin = "J";
                    }
                    
                    if (admin.equals("Nej")){
                        nuvarandeAdmin = "N";
                    }
                    
                    String nyaAgenten = ("INSERT INTO Agent VALUES (" + nyaID + ",'" + namn + "','" + telnmr + "','" + anstdatum + "','" + nuvarandeAdmin + "','" + losen + "'," + hamtaOmradesID + ")");
                    idb.insert(nyaAgenten);
                    JOptionPane.showMessageDialog(null, "En ny agent har registrerats!");
                   
                } catch (InfException ettUndantag){
                    JOptionPane.showMessageDialog (null, "Något gick fel!");
                }
        }
    }//GEN-LAST:event_BTNregistreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NyregistreraAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNregistrera;
    private javax.swing.JComboBox<String> CBomrade;
    private javax.swing.JComboBox<String> CBvaljAdmin;
    private javax.swing.JLabel JLAdmin;
    private javax.swing.JLabel JLDatum;
    private javax.swing.JLabel JLLosen;
    private javax.swing.JLabel JLNamn;
    private javax.swing.JLabel JLOmråde;
    private javax.swing.JLabel JLTelnr;
    private javax.swing.JLabel JRubrik;
    private javax.swing.JTextField TxtDatum;
    private javax.swing.JTextField TxtNamn;
    private javax.swing.JTextField TxtTelnr;
    private javax.swing.JTextField Txtlosen;
    // End of variables declaration//GEN-END:variables
}
