/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;



import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
/**
 *
 * @author amandademir, piava
 */
public class NyregistreraUtrustning extends javax.swing.JFrame {
 
    private InfDB idb;
    /**
     * Creates new form NyregistreraUtrustning
     */
    public NyregistreraUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLRubrik = new javax.swing.JLabel();
        JLRegUtrustning = new javax.swing.JLabel();
        BtnRegistrera = new javax.swing.JButton();
        TxtUtrustning = new javax.swing.JTextField();
        JComboBoxUtrustning = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbTeknik = new javax.swing.JLabel();
        txtTeknik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLRubrik.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        JLRubrik.setText("Registrera ny utrustning");

        JLRegUtrustning.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        JLRegUtrustning.setText("Ange utrustning för att registrera:");

        BtnRegistrera.setText("Registrera");
        BtnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistreraActionPerformed(evt);
            }
        });

        JComboBoxUtrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Vapen", "Kommunikation", "Teknik" }));
        JComboBoxUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxUtrustningActionPerformed(evt);
            }
        });

        jLabel1.setText("Namn på utrustning:");

        lbTeknik.setText("Typ av teknik:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JComboBoxUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTeknik, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(TxtUtrustning))))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(JLRegUtrustning))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(BtnRegistrera))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTeknik)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JLRubrik)
                .addGap(31, 31, 31)
                .addComponent(JLRegUtrustning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JComboBoxUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTeknik)
                    .addComponent(txtTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(BtnRegistrera)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistreraActionPerformed
    if(Validering.tomRuta(TxtUtrustning))
    
    try{
        String namn = TxtUtrustning.getText();
            String uID = idb.getAutoIncrement("Utrustning", "Utrustnings_ID");
            int nyaID = Integer.parseInt(uID);
            String utrustning =  JComboBoxUtrustning.getSelectedItem().toString();
            String boxUtrustning = (" SELECT BENAMNING FROM UTRUSTNING");
            String getUtrustning = idb.fetchSingle(boxUtrustning);
            String nyUtrustning = ("INSERT INTO UTRUSTNING VALUES(" + nyaID + ",'" + namn + "')");
            System.out.println(nyUtrustning);
            idb.insert(nyUtrustning);
            String utrustingFöremål = txtTeknik.getText();
            
            if(utrustning.equals("Kommunikation")){
                idb.insert("INSERT INTO Kommunikation VALUES(" + nyaID + ",'"+ utrustingFöremål +"')");
                
            }
          if(utrustning.equals("Teknik")){
                idb.insert("INSERT INTO Teknik VALUES(" + nyaID + ", ' " + utrustingFöremål + "')");
               
            } 

            if(utrustning.equals("Vapen")){
                idb.insert("INSERT INTO Vapen VALUES(" + nyaID + ", '" + utrustingFöremål + "')" );
               
            } 
            

        JOptionPane.showMessageDialog(null, "Registreringen klar!");
            
    } catch (InfException ettUndantag) {   
        JOptionPane.showMessageDialog(null, " Registrering gick ej!");        }    
    }//GEN-LAST:event_BtnRegistreraActionPerformed

    private void JComboBoxUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxUtrustningActionPerformed
        String utrustning = JComboBoxUtrustning.getSelectedItem().toString(); 

           if(utrustning.equals("Kommunikation")){
               lbTeknik.setEnabled(true);
               lbTeknik.setText(" Överforningsteknik:");
           }
           if(utrustning.equals("Teknik")){
              lbTeknik.setEnabled(true);
               lbTeknik.setText("Kraftkalla:");
           }
           if(utrustning.equals("Vapen")){
               lbTeknik.setEnabled(true);
               lbTeknik.setText("Kaliber:");
           }

    }//GEN-LAST:event_JComboBoxUtrustningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NyregistreraUtrustning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrera;
    private javax.swing.JComboBox<String> JComboBoxUtrustning;
    private javax.swing.JLabel JLRegUtrustning;
    private javax.swing.JLabel JLRubrik;
    private javax.swing.JTextField TxtUtrustning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbTeknik;
    private javax.swing.JTextField txtTeknik;
    // End of variables declaration//GEN-END:variables
}
