/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
/**
 *
 * @author amandademir
 */
public class RaderaUtrustning extends javax.swing.JFrame {
 
    private InfDB idb; 
    /**
     * Creates new form RaderaUtrustning
     */
    public RaderaUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
        fillComboboxUtrustningar();
    }

    private void fillComboboxUtrustningar(){
    JComboBoxRaderaUtrustning.removeAllItems();
    String question = "SELECT Benamning FROM Utrustning";
    
    ArrayList<String> Utrustningar = new ArrayList<String>();
    try {
    Utrustningar= idb.fetchColumn(question);
    
    for(String utrustning: Utrustningar)
    {
      JComboBoxRaderaUtrustning.addItem(utrustning);
    }
    }   catch (InfException ettUndantag) {
            Logger.getLogger(RaderaUtrustning.class.getName()).log(Level.SEVERE, null, ettUndantag);
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLRubrik = new javax.swing.JLabel();
        JLRaderaUtrustning = new javax.swing.JLabel();
        JComboBoxRaderaUtrustning = new javax.swing.JComboBox<>();
        BtnRaderaUtrustning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLRubrik.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        JLRubrik.setText("Radera Utrustning");

        JLRaderaUtrustning.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JLRaderaUtrustning.setText("Radera Utrustning från systemet");

        JComboBoxRaderaUtrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Neuralyzer", "Carbonizer" }));

        BtnRaderaUtrustning.setText("Radera");
        BtnRaderaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaderaUtrustningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRaderaUtrustning)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JComboBoxRaderaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLRaderaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(JLRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLRaderaUtrustning)
                .addGap(27, 27, 27)
                .addComponent(JComboBoxRaderaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(BtnRaderaUtrustning)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRaderaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaderaUtrustningActionPerformed
     String utrustningsNamn = String.valueOf(JComboBoxRaderaUtrustning.getSelectedItem().toString());
            
        try {
        String utrustning = idb.fetchSingle("SELECT Utrustnings_ID FROM Utrustning WHERE Benamning = '"+utrustningsNamn+"'");
        {    
        idb.delete("DELETE FROM Utrustning WHERE Benamning = '" + utrustningsNamn + "'");
        JOptionPane.showMessageDialog(null, "Utrustning med Namnet " + utrustningsNamn + " är bortaget!"); 
        }
        } catch (InfException ettUndantag) {
                Logger.getLogger(RaderaUtrustning.class.getName()).log(Level.SEVERE, null, ettUndantag);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_BtnRaderaUtrustningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaderaUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaderaUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaderaUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaderaUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaderaUtrustning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRaderaUtrustning;
    private javax.swing.JComboBox<String> JComboBoxRaderaUtrustning;
    private javax.swing.JLabel JLRaderaUtrustning;
    private javax.swing.JLabel JLRubrik;
    // End of variables declaration//GEN-END:variables
}
