/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author amandademir
 */
public class RaderaAgent extends javax.swing.JFrame {

    private InfDB idb; 
    /**
     * Creates new form RaderaAgent
     */
    public RaderaAgent(InfDB idb) {
        initComponents(); 
        this.idb = idb;
        fyllComboboxAgenter();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void fyllComboboxAgenter(){
    JComboBoxRaderaAgent.removeAllItems();
    String question = "SELECT Namn FROM Agent";
    
    ArrayList<String> Agenter ;
    try {
    Agenter= idb.fetchColumn(question);
    
    for(String agent: Agenter)
    {
      JComboBoxRaderaAgent.addItem(agent);
    }
    }   catch (InfException ettUndantag) {
            Logger.getLogger(RaderaAgent.class.getName()).log(Level.SEVERE, null, ettUndantag);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLRubrik = new javax.swing.JLabel();
        JLRaderaAgent = new javax.swing.JLabel();
        JComboBoxRaderaAgent = new javax.swing.JComboBox<>();
        BtnRadera = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLRubrik.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        JLRubrik.setText("Radera Agent");

        JLRaderaAgent.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        JLRaderaAgent.setText("Välj agent att radera");

        JComboBoxRaderaAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Agent K", "Agent J", "Agent Z", "Agent O" }));

        BtnRadera.setText("Radera");
        BtnRadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaderaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 2, 10)); // NOI18N
        jLabel1.setText("Här kan du som admin radera en eller flera agenter ur systemet.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLRaderaAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JComboBoxRaderaAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnRadera)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JLRubrik)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(JLRaderaAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JComboBoxRaderaAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(BtnRadera)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaderaActionPerformed
    String agentNamn = String.valueOf(JComboBoxRaderaAgent.getSelectedItem().toString());
 
            
    try {
        String agent = idb.fetchSingle("SELECT Agent_ID FROM Agent WHERE Namn = '"+agentNamn+"'");
        
        {    
        idb.delete("DELETE FROM Agent WHERE Namn = '" + agentNamn + "'");
        JOptionPane.showMessageDialog(null, "Agent med Namnet " + agentNamn + " är bortaget!"); 
        }
 
        } catch (InfException ettUndantag) {
                Logger.getLogger(RaderaAgent.class.getName()).log(Level.SEVERE, null, ettUndantag);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_BtnRaderaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaderaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaderaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaderaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaderaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RaderaAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRadera;
    private javax.swing.JComboBox<String> JComboBoxRaderaAgent;
    private javax.swing.JLabel JLRaderaAgent;
    private javax.swing.JLabel JLRubrik;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
