/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIBprojekt22;

import oru.inf.InfDB;

/**
 *
 * @author piava
 */
public class RedigeraAlien extends javax.swing.JFrame {

    private static InfDB idb;
    
    public RedigeraAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBrubrik = new java.awt.Label();
        BTNnyRegAlien = new java.awt.Button();
        BTNvisaAlieninfo = new java.awt.Button();
        BTNListaAlienPlats = new java.awt.Button();
        label2 = new java.awt.Label();
        BTNListaAlienRas = new java.awt.Button();
        BTNListaAlienDatum = new java.awt.Button();
        BTNandraAlieninfo = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBrubrik.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        LBrubrik.setText("Redigera Alien");

        BTNnyRegAlien.setBackground(new java.awt.Color(255, 255, 255));
        BTNnyRegAlien.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNnyRegAlien.setLabel("Nyregistrera alien");
        BTNnyRegAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNnyRegAlienActionPerformed(evt);
            }
        });

        BTNvisaAlieninfo.setBackground(new java.awt.Color(255, 255, 255));
        BTNvisaAlieninfo.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNvisaAlieninfo.setLabel("Visa alieninformation");
        BTNvisaAlieninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNvisaAlieninfoActionPerformed(evt);
            }
        });

        BTNListaAlienPlats.setBackground(new java.awt.Color(255, 255, 255));
        BTNListaAlienPlats.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNListaAlienPlats.setLabel("Plats");
        BTNListaAlienPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNListaAlienPlatsActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        label2.setText("Lista Alien utifrån:");

        BTNListaAlienRas.setBackground(new java.awt.Color(255, 255, 255));
        BTNListaAlienRas.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNListaAlienRas.setLabel("Ras");
        BTNListaAlienRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNListaAlienRasActionPerformed(evt);
            }
        });

        BTNListaAlienDatum.setBackground(new java.awt.Color(255, 255, 255));
        BTNListaAlienDatum.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNListaAlienDatum.setLabel("Datum");
        BTNListaAlienDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNListaAlienDatumActionPerformed(evt);
            }
        });

        BTNandraAlieninfo.setBackground(new java.awt.Color(255, 255, 255));
        BTNandraAlieninfo.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNandraAlieninfo.setLabel("Ändra alieninformation");
        BTNandraAlieninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNandraAlieninfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTNvisaAlieninfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNandraAlieninfo, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addComponent(BTNnyRegAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BTNListaAlienPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BTNListaAlienDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BTNListaAlienRas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LBrubrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LBrubrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(BTNvisaAlieninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNandraAlieninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNnyRegAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNListaAlienRas, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTNListaAlienPlats, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(BTNListaAlienDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNvisaAlieninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNvisaAlieninfoActionPerformed
        new VisaAlienInformation(idb).setVisible(true);
    }//GEN-LAST:event_BTNvisaAlieninfoActionPerformed

    private void BTNandraAlieninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNandraAlieninfoActionPerformed
        // TODO add your handling code here:
        new AndraAlienInformation(idb).setVisible(true);
    }//GEN-LAST:event_BTNandraAlieninfoActionPerformed

    private void BTNnyRegAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNnyRegAlienActionPerformed
        // TODO add your handling code here:
        new NyregistreraAlien(idb).setVisible(true);
    }//GEN-LAST:event_BTNnyRegAlienActionPerformed

    private void BTNListaAlienPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNListaAlienPlatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNListaAlienPlatsActionPerformed

    private void BTNListaAlienDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNListaAlienDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNListaAlienDatumActionPerformed

    private void BTNListaAlienRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNListaAlienRasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNListaAlienRasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RedigeraAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BTNListaAlienDatum;
    private java.awt.Button BTNListaAlienPlats;
    private java.awt.Button BTNListaAlienRas;
    private java.awt.Button BTNandraAlieninfo;
    private java.awt.Button BTNnyRegAlien;
    private java.awt.Button BTNvisaAlieninfo;
    private java.awt.Label LBrubrik;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
